global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["52.203.29.179:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["52.203.29.179:9100"]
  
  - job_name: "docker-exporte"
    static_configs:
      - targets: ["52.203.29.179:9417"]
